import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  Github,
  HelpCircle,
  Image as LucideImage,
  Laptop,
  Loader2,
  LogIn,
  LogOut,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  PlusCircle,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  UserPlus,
  X,
  Star,
  Briefcase,
  DollarSign,
  Languages,
  MapPin,
  Users,
  Award,
  BookOpen,
  CalendarDays,
  Filter,
  LayoutGrid,
  List,
  MessageSquare,
  Search,
  Sparkles,
  ShieldCheck,
  Brain,
  Heart,
  Link as LinkIcon,
  Globe,
  Clock,
  Edit3,
  Eye,
  PanelLeft,
  Menu,
  Home
} from "lucide-react";

export type Icon = typeof ChevronLeft;

export const Icons = {
  logo: Briefcase,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: LucideImage,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  check: Check,
  plusCircle: PlusCircle,
  logIn: LogIn,
  logOut: LogOut,
  userPlus: UserPlus,
  command: Command,
  star: Star,
  starFilled: (props: React.ComponentProps<typeof Star>) => <Star {...props} fill="currentColor" />,
  dollarSign: DollarSign,
  languages: Languages,
  mapPin: MapPin,
  users: Users,
  award: Award,
  bookOpen: BookOpen,
  calendarDays: CalendarDays,
  filter: Filter,
  layoutGrid: LayoutGrid,
  list: List,
  messageSquare: MessageSquare,
  search: Search,
  sparkles: Sparkles,
  shieldCheck: ShieldCheck,
  brain: Brain,
  briefcase: Briefcase,
  heart: Heart,
  link: LinkIcon,
  globe: Globe,
  clock: Clock,
  edit: Edit3,
  view: Eye,
  panelLeft: PanelLeft,
  menu: Menu,
  home: Home,
};
